
static class MenuEnums
{
    public enum Main { MANAGECONTACTS, MANAGECATEGORY, SENDEMAIL, SENDSMS, EXIT }
    public enum Contact { ADDCONTACT, DELETECONTACT, UPDATECONTACT, READCONTACT, BACK }
    public enum Category { ADDCATEGORY, DELETECATEGORY, UPDATECATEGORY, READCATEGORY, BACK }

}